In [3]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.cross_validation import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
import os

In [4]:
os.chdir("C:/Users/sunil/Desktop/Practice Data")

In [6]:
credit=pd.read_csv("tree.csv")

In [7]:
credit.head()

CREDIT_RATING    AGE  INCOME CREDIT_CARDS    EDUCATION    CAR_LOANS
0           Bad  36.22  Medium    5 or more      College  More than 2
1           Bad  21.99  Medium    5 or more      College  More than 2
2           Bad  29.17     Low    5 or more  High school  More than 2
3           Bad  32.75     Low    5 or more      College    None or 1
4           Bad  36.77  Medium    5 or more      College  More than 2

#### Spliting the dataset into train and test

In [9]:
y=credit.iloc[:,:-5]
x=credit.iloc[:,1:6]

In [15]:
x2 = pd.get_dummies(x, columns=['INCOME','CAR_LOANS','EDUCATION','CREDIT_CARDS'])
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y2=labelencoder_y.fit_transform(y)

C:\Users\sunil\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
x_train,x_test,y_train,y_test=train_test_split(x2,y2,test_size=0.30,random_state=0)

In [64]:
tree=DecisionTreeClassifier(criterion="entropy",random_state=0)

In [65]:
tree=tree.fit(x_train,y_train)

In [66]:
train_ypred=tree.predict(x_train)
print(train_ypred)

[0 0 0 ... 0 0 1]


In [67]:
cm=confusion_matrix(train_ypred,y_train)
cm

array([[ 709,    7],
       [   0, 1008]], dtype=int64)

In [68]:
cm1=classification_report(train_ypred,y_train)
print(cm1)

             precision    recall  f1-score   support

          0       1.00      0.99      1.00       716
          1       0.99      1.00      1.00      1008

avg / total       1.00      1.00      1.00      1724



In [69]:
test_ypred=tree.predict(x_test)
cm2=confusion_matrix(test_ypred,y_test)
print(cm2)
cm3=classification_report(test_ypred,y_test)
print(cm3)

[[216 100]
 [ 95 329]]
             precision    recall  f1-score   support

          0       0.69      0.68      0.69       316
          1       0.77      0.78      0.77       424

avg / total       0.74      0.74      0.74       740



In [ ]:
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

In [71]:
dot_data = StringIO()
export_graphviz(tree, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)

In [72]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [ ]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import tree
from sklearn.datasets import load_wine
from IPython.display import SVG
from graphviz import Source
# from IPython.display import display